project_id = "kjabpmcsiluvtxmbbfbg"

[functions.suspend-expired-trials]
verify_jwt = false

[functions.handle-upgrade-webhook]
verify_jwt = false

[functions.send-password-reset]
verify_jwt = false

[functions.send-test-email]  
verify_jwt = false

[functions.send-signup-confirmation]
verify_jwt = false

[functions.custom-signup]
verify_jwt = false

[functions.cleanup-campaigns]
verify_jwt = false

[functions.generate-headline]
verify_jwt = true

[functions.transcribe-audio]
verify_jwt = true

[functions.generate-page-config]
verify_jwt = true

[functions.transcribe-page-prompt]
verify_jwt = true